services:
  - type: web
    name: hireflow-pro
    runtime: docker
    plan: free
    rootDir: HireFlowPro
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: HireFlowPro
      - key: Jwt__Audience
        value: HireFlowPro
      - key: DATABASE_URL
        fromDatabase:
          name: hireflow-db
          property: connectionString

databases:
  - name: hireflow-db
    plan: free
    databaseName: hireflow_pro
    user: hireflow
